#!/usr/bin/env python3
# Build the consolidated, deduplicated findings.json for the gluckbags.com SEO audit.
# Merges the deterministic auto-findings + the adversarially-verified workflow findings,
# collapsing the ~51 raw items (heavy root-cause overlap) into a clean curated set.
import json, os

WORK = "/Users/cromero/projects/gluck-bags-web/relevamiento-seo-gluckbags-com"
EV = os.path.join(WORK, "evidence")

findings = [
  {
    "id": "01",
    "title": "Canonical cross-dominio: gluckbags.com cede toda su autoridad a un dominio gemelo vivo (gluck.nexttech.com.ar)",
    "severity": "critical",
    "category": "Canonical / Indexación",
    "dimension": "url-canonicalization",
    "scope": "Todo el sitio (home + todas las PDP + variantes de URL)",
    "symptom": "Cada página de gluckbags.com declara como canónica una URL de OTRO dominio: gluck.nexttech.com.ar. Ese segundo dominio está VIVO, sirve contenido idéntico y se auto-canonicaliza. Resultado: gluckbags.com le dice a Google «la versión buena de esta página vive en gluck.nexttech.com.ar», así que Google indexa y rankea el alias y trata al dominio de marca como un duplicado que apunta hacia afuera. El dominio de marca puede quedar directamente fuera del índice bajo su propio nombre.",
    "evidence": "Verificado en vivo (curl UA Chrome, HTTP 200, sin captcha):\n\n# gluckbags.com/  (dominio de marca)\n<link rel=\"canonical\" href=\"https://gluck.nexttech.com.ar/\">\n<meta property=\"og:url\"   content=\"https://gluck.nexttech.com.ar/\">\n<meta property=\"og:image\" content=\"https://gluck.nexttech.com.ar/static/img/og-image.jpg\">\n\n# gluck.nexttech.com.ar/  (el gemelo) -> HTTP 200, mismo <title> 'GLÜCK · Bolsos minimalistas...'\n<link rel=\"canonical\" href=\"https://gluck.nexttech.com.ar/\">   # se auto-canonicaliza\n\nCausa raíz: el config de producción SITE_URL/site_url está apuntado al alias de staging. La home emite el canonical desde site_url (app/templates/index.html:23) y og:url/og:image están hardcodeados al alias en base_public.html y product_detail.html.",
    "recommendation": "1) Setear en producción SITE_URL=https://gluckbags.com y corregir los og:url/og:image hardcodeados en base_public.html y product_detail.html. 2) Redirigir 301 todo gluck.nexttech.com.ar -> https://gluckbags.com (o, si debe seguir vivo, ponerlo noindex y canonical hacia gluckbags.com). 3) Verificar el dominio en Google Search Console y pedir reindexación. Es el arreglo de mayor impacto y debe ir primero.",
    "evidenceKind": "serp",
    "serp": {"title": "GLÜCK · Bolsos minimalistas de cuero vegano", "url": "https://gluck.nexttech.com.ar/", "description": "GLÜCK — Bolsos minimalistas de cuero vegano. Carteras y bolsos de cuero vegano, hechos a mano con un diseño minimalista y atemporal."},
    "evidenceFile": os.path.join(EV, "01-serp-wrongdomain.png"),
    "status": "PENDIENTE",
  },
  {
    "id": "02",
    "title": "Duplicación de host: www, no-www y http:// devuelven 200 sin redirigir al canónico",
    "severity": "high",
    "category": "Canonical / Indexación",
    "dimension": "url-canonicalization",
    "scope": "Hosts: gluckbags.com, www.gluckbags.com, http://(www.)gluckbags.com",
    "symptom": "Las cuatro variantes de host devuelven 200 con el mismo contenido y ninguna redirige a una versión única. No hay canonicalización de host: Google puede rastrear e indexar el mismo contenido en varios hosts (más el gemelo nexttech del hallazgo 01), repartiendo señales y generando duplicados.",
    "evidence": "Verificado en vivo (curl, sin -L):",
    "recommendation": "Elegir un host canónico (https://gluckbags.com) y redirigir 301 todas las variantes (www->apex, http->https). En Cloudflare: activar «Always Use HTTPS» y una Bulk Redirect / Rule para www. Confirmar que la única versión 200 sea https://gluckbags.com/.",
    "evidenceKind": "table",
    "evidenceTable": [
      {"URL": "http://gluckbags.com/", "Status": "200", "Redirige a": "— (no redirige)"},
      {"URL": "https://www.gluckbags.com/", "Status": "200", "Redirige a": "— (no redirige)"},
      {"URL": "http://www.gluckbags.com/", "Status": "200", "Redirige a": "— (no redirige)"},
      {"URL": "https://gluckbags.com/ (esperado: único 200)", "Status": "200", "Redirige a": "—"},
    ],
    "status": "PENDIENTE",
  },
  {
    "id": "03",
    "title": "No hay páginas de identidad/confianza (Nosotras, Contacto, envíos, cambios, términos) en una tienda que cobra",
    "severity": "high",
    "category": "Contenido / E-E-A-T",
    "dimension": "content-quality-eeat",
    "scope": "Todo el sitio (no existe ninguna ruta de estas páginas)",
    "symptom": "Para un e-commerce, Google y los usuarios esperan señales de confianza: quiénes son, cómo contactar, política de envíos, cambios/devoluciones y términos. Ninguna existe (todas 404) y no hay un canal de contacto en el sitio (sólo CTAs a Instagram). Es un hueco de E-E-A-T y de conversión.",
    "evidence": "Verificado en vivo (curl) — todas 404:",
    "recommendation": "Agregar páginas reales e indexables: Nosotras (historia de marca), Contacto (con canal real: email/WhatsApp + Instagram), Envíos, Cambios y devoluciones, y Términos/Privacidad. Enlazarlas desde el footer. Suma confianza, contenido indexable y palabras clave de marca.",
    "evidenceKind": "table",
    "evidenceTable": [
      {"URL probada": "/nosotras", "Status": "404"},
      {"URL probada": "/contacto", "Status": "404"},
      {"URL probada": "/envios", "Status": "404"},
      {"URL probada": "/cambios-y-devoluciones", "Status": "404"},
      {"URL probada": "/terminos", "Status": "404"},
      {"URL probada": "/privacidad", "Status": "404"},
      {"URL probada": "/faq", "Status": "404"},
    ],
    "status": "PENDIENTE",
  },
  {
    "id": "04",
    "title": "Sin sitemap.xml y robots.txt no lo declara: el descubrimiento depende sólo de los links de la home",
    "severity": "medium",
    "category": "Sitemap / Descubrimiento",
    "dimension": "indexability-crawl",
    "scope": "sitemap.xml / robots.txt",
    "symptom": "No existe ningún sitemap (404 en todas las ubicaciones habituales) y robots.txt no tiene línea Sitemap:. Para un sitio nuevo sin backlinks, un sitemap acelera el descubrimiento y, sobre todo, permite enviarlo en Search Console y monitorear cobertura por URL.",
    "evidence": "Verificado en vivo (curl) — sin sitemap en ninguna ruta habitual; robots.txt sin línea 'Sitemap:':\n\n404  https://gluckbags.com/sitemap.xml\n404  https://gluckbags.com/sitemap_index.xml\n404  https://gluckbags.com/sitemap-index.xml\n404  https://gluckbags.com/wp-sitemap.xml\n\n# robots.txt -> no contiene ninguna línea 'Sitemap: ...'",
    "recommendation": "Agregar una ruta /sitemap.xml que liste la home y los productos publicados (con <lastmod>), declarar 'Sitemap: https://gluckbags.com/sitemap.xml' en robots.txt y enviarlo en Search Console. Generarlo con las URLs canónicas correctas (gluckbags.com) una vez resuelto el hallazgo 01.",
    "evidenceKind": "code",
    "status": "PENDIENTE",
  },
  {
    "id": "05",
    "title": "Cero datos estructurados (JSON-LD) en todo el sitio: sin Organization/WebSite, sin Product, sin BreadcrumbList",
    "severity": "medium",
    "category": "Datos estructurados",
    "dimension": "structured-data",
    "scope": "Home + todas las PDP",
    "symptom": "Ninguna página emite JSON-LD ni microdata. La home no declara Organization/WebSite (pierde knowledge panel y sitelinks searchbox); las PDP no declaran Product (pierden el rich result de producto) pese a que ya se auto-identifican como producto para social (og:type=product) y tienen nombre, imagen, marca y categoría en el DOM. Tampoco hay BreadcrumbList.",
    "evidence": "Verificado en vivo y en artefactos (DOM renderizado post-JS):\n\ngrep -ci 'application/ld+json'  -> 0  (home, producto-1, producto-2, producto-3)\ngrep -ci 'itemtype|itemscope'  -> 0  (sin microdata/RDFa)\nseo-producto-1.json -> jsonLdCount: 0, jsonLdTypes: [], microdataTypes: []\n\n# pero la PDP YA se declara producto para social:\n<meta property=\"og:type\" content=\"product\">",
    "recommendation": "Agregar JSON-LD: en la home Organization (logo, sameAs a Instagram) + WebSite; en cada PDP Product (name, image absoluta, brand 'GLÜCK', category, description). IMPORTANTE: el precio es 'Consultar' (venta por Instagram), así que NO inventar offers.price — sería markup que no coincide con lo visible (riesgo de acción manual). Declarar Product sin offers, o con Offer availability InStock + url al canal, y recién agregar price/priceCurrency (ARS) cuando haya un precio numérico real. Sumar BreadcrumbList cuando exista una URL de categoría real (ver hallazgo 12).",
    "evidenceKind": "code",
    "status": "PENDIENTE",
  },
  {
    "id": "06",
    "title": "Sin canonical propio: parámetros arbitrarios e IDs con ceros a la izquierda sirven 200 duplicado",
    "severity": "medium",
    "category": "Canonical / Indexación",
    "dimension": "indexability-crawl",
    "scope": "Home con query params + /producto/<id> (PDP sin canonical)",
    "symptom": "Las PDP no tienen rel=canonical en absoluto, y la home/PDP aceptan basura en la URL devolviendo 200 con contenido idéntico: ?s=cualquier-cosa, ?utm_source=..., y hasta IDs con ceros a la izquierda (/producto/01, /producto/001) que Flask resuelve al mismo producto. Sin un canonical propio que normalice, cada variante es una URL duplicada e indexable (trampa de rastreo). Hoy lo único que las 'salva' es el canonical del hallazgo 01… que apunta al dominio equivocado.",
    "evidence": "Verificado en vivo (curl) — todas 200 con el mismo contenido:",
    "recommendation": "Emitir en TODA página un canonical auto-referencial con los parámetros removidos (home -> https://gluckbags.com/; PDP -> https://gluckbags.com/producto/<id>). Ignorar parámetros desconocidos y, opcionalmente, normalizar IDs no canónicos (01 -> 404 o 301 a 1). Esto colapsa todas las variantes a una sola URL canónica del dominio correcto.",
    "evidenceKind": "table",
    "evidenceTable": [
      {"URL": "https://gluckbags.com/?s=seo", "Status": "200", "Contenido": "= home", "Canonical propio": "no (apunta al alias)"},
      {"URL": "https://gluckbags.com/?utm_source=newsletter", "Status": "200", "Contenido": "= home", "Canonical propio": "no (apunta al alias)"},
      {"URL": "https://gluckbags.com/producto/1", "Status": "200", "Contenido": "Tote Cognac", "Canonical propio": "— (sin canonical)"},
      {"URL": "https://gluckbags.com/producto/01", "Status": "200", "Contenido": "= producto 1", "Canonical propio": "— (sin canonical)"},
      {"URL": "https://gluckbags.com/producto/001", "Status": "200", "Contenido": "= producto 1", "Canonical propio": "— (sin canonical)"},
    ],
    "status": "PENDIENTE",
  },
  {
    "id": "07",
    "title": "Contenido de producto delgado y 100% plantillado",
    "severity": "medium",
    "category": "Contenido",
    "dimension": "content-quality-eeat",
    "scope": "Todas las PDP (/producto/1..N)",
    "symptom": "Las fichas tienen ~51 palabras y el copy es una fórmula con sólo el nombre/categoría cambiados: title '<Nombre> · GLÜCK', description '<Nombre> · <Categoría> — GLÜCK, cuero vegano hecho a mano.' y cuerpo mínimo. Poco contenido único para rankear por términos de producto y baja diferenciación entre fichas.",
    "evidence": "De los artefactos (wordCount) y el patrón de títulos/descriptions:",
    "recommendation": "Escribir descripciones únicas por producto: materiales, medidas, capacidad, detalles de confección, cuidados y ocasión de uso. Subir el contenido por ficha bastante por encima de las ~50 palabras actuales y evitar la fórmula repetida.",
    "evidenceKind": "table",
    "evidenceTable": [
      {"URL": "/producto/1 (Tote Cognac)", "Palabras": "51", "title": "Tote Cognac · GLÜCK", "description": "Tote Cognac · Tote — GLÜCK, cuero vegano hecho a mano."},
      {"URL": "/producto/2 (Tote Gris)", "Palabras": "51", "title": "Tote Gris · GLÜCK", "description": "Tote Gris · Tote — GLÜCK, cuero vegano hecho a mano."},
      {"URL": "/producto/3 (Crossbody Rosa)", "Palabras": "52", "title": "Crossbody Rosa · GLÜCK", "description": "Crossbody Rosa · Mini Bag — GLÜCK, cuero vegano hecho a mano."},
      {"URL": "/ (home, referencia)", "Palabras": "369", "title": "GLÜCK · Bolsos minimalistas de cuero vegano", "description": "—"},
    ],
    "status": "PENDIENTE",
  },
  {
    "id": "08",
    "title": "http:// se sirve con 200 en texto plano: sin redirección 301 a https ni HSTS",
    "severity": "medium",
    "category": "Infra / Seguridad",
    "dimension": "url-canonicalization",
    "scope": "http://gluckbags.com/",
    "symptom": "La home responde 200 sobre HTTP sin redirigir a HTTPS, y no hay cabecera HSTS. Además de duplicar contenido en http/https (hallazgo 02), sirve la página en texto plano y pierde el refuerzo de seguridad que Google valora.",
    "evidence": "curl -I http://gluckbags.com/ :\n\nHTTP/1.1 200 OK\nCf-Cache-Status: DYNAMIC\nCF-RAY: ...\n# (sin 'Location:' a https, sin 'Strict-Transport-Security')",
    "recommendation": "Activar «Always Use HTTPS» en Cloudflare (301 http->https) y agregar HSTS (Strict-Transport-Security: max-age=31536000; includeSubDomains; preload) una vez confirmado que todo va por https.",
    "evidenceKind": "code",
    "status": "PENDIENTE",
  },
  {
    "id": "09",
    "title": "Las previews sociales se atribuyen al dominio equivocado (og:url y og:image en gluck.nexttech.com.ar)",
    "severity": "medium",
    "category": "Social / Open Graph",
    "dimension": "social-og-quality",
    "scope": "Home + todas las PDP",
    "symptom": "Al compartir cualquier URL de gluckbags.com en WhatsApp/Facebook/Twitter, la tarjeta muestra y enlaza a gluck.nexttech.com.ar, y la imagen se sirve desde ese dominio. La marca pierde la atribución de todo lo que se comparte (mismo origen que el hallazgo 01).",
    "evidence": "Verificado en vivo (curl) en la home y en /producto/1:\n\n<meta property=\"og:url\"   content=\"https://gluck.nexttech.com.ar/\">\n<meta property=\"og:image\" content=\"https://gluck.nexttech.com.ar/static/img/og-image.jpg\">\n# en PDP: og:url y og:image -> https://gluck.nexttech.com.ar/...",
    "recommendation": "Mismo arreglo que el hallazgo 01: SITE_URL=https://gluckbags.com y corregir los og:url/og:image hardcodeados. Revalidar con el Sharing Debugger de Facebook y la Card Validator de Twitter/X.",
    "evidenceKind": "photo",
    "evidenceFile": os.path.join(EV, "13-social-wrongdomain.png"),
    "status": "PENDIENTE",
  },
  {
    "id": "10",
    "title": "Las páginas de producto no enlazan a otros productos (sin módulo de relacionados)",
    "severity": "medium",
    "category": "Enlazado interno",
    "dimension": "internal-linking",
    "scope": "Todas las PDP",
    "symptom": "Desde una ficha sólo se puede volver a la grilla (#shop) o ir a Instagram. No hay enlaces a otros productos, así que el link equity no fluye entre fichas y Google tiene un único camino (la home) para llegar a cada producto. Peor descubrimiento y peor distribución de autoridad interna.",
    "evidence": "Los únicos enlaces internos de una PDP son el «← Volver a los bolsos» (a /#shop) y los del header/footer (todos anclas a la home /#...) más el CTA a Instagram (externo). No hay ningún <a href> a otro /producto/<id>.",
    "recommendation": "Agregar un módulo «También te puede gustar» / «Otros bolsos» con 3-4 productos enlazados al pie de cada PDP. Mejora el enlazado interno, el descubrimiento y el tiempo en sitio.",
    "evidenceKind": "code",
    "status": "PENDIENTE",
  },
  {
    "id": "11",
    "title": "Las tarjetas de «categoría» apuntan todas al mismo ancla #shop: no hay arquitectura de categorías",
    "severity": "low",
    "category": "Enlazado interno",
    "dimension": "internal-linking",
    "scope": "Home (bloque de categorías) ",
    "symptom": "Las cuatro categorías (Tote / Mini Bag / Bucket Bag / Clutch) se muestran como tarjetas pero todas llevan al mismo ancla #shop de la home. No existen URLs de categoría reales (ni en el sitio ni en sitemap), así que no hay páginas indexables que puedan rankear por «cartera tote», «mini bag», etc.",
    "evidence": "Las 4 tarjetas de categoría resuelven al mismo destino (#shop). No hay rutas /categoria/<nombre> (devolverían 404). La categoría existe sólo como etiqueta/CSS-class, no como página.",
    "recommendation": "Crear páginas de categoría reales e indexables (/categoria/tote, etc.) que listen los productos de cada tipo, enlazadas desde estas tarjetas y desde el sitemap. Habilita rankear por términos de categoría y construir BreadcrumbList (hallazgo 05).",
    "evidenceKind": "code",
    "status": "PENDIENTE",
  },
  {
    "id": "12",
    "title": "La página 404 es el default crudo de Werkzeug: lang=en, sin navegación ni marca",
    "severity": "low",
    "category": "Errores / UX",
    "dimension": "indexability-crawl",
    "scope": "Cualquier URL inexistente",
    "symptom": "El 404 devuelve el estado correcto (bien, no es soft-404) pero es la página default del servidor: «Not Found / The requested URL was not found...» en inglés sobre un sitio en español, sin header, sin navegación de vuelta al sitio y sin la analítica de Umami. Es un callejón sin salida para el usuario y el crawler.",
    "evidence": "Captura en vivo de https://gluckbags.com/<url-inexistente> (estado 404, html lang=\"en\").",
    "recommendation": "Registrar un handler 404 con una plantilla propia: html lang=\"es\", header/footer del sitio, un mensaje de marca y enlaces de vuelta (home, bolsos). Incluir el tag de Umami para medir el tráfico de error.",
    "evidenceKind": "photo",
    "evidenceFile": os.path.join(EV, "12-404.png"),
    "status": "PENDIENTE",
  },
  {
    "id": "13",
    "title": "Calidad de tarjeta social en productos: og:image vertical recortada, sin dimensiones y Twitter Card incompleta",
    "severity": "low",
    "category": "Social / Open Graph",
    "dimension": "social-og-quality",
    "scope": "Todas las PDP",
    "symptom": "En las fichas, og:image usa la foto vertical del producto (787x1400, relación ~0.56:1): en una tarjeta summary_large_image (1.91:1) se recorta fuerte. Además falta og:image:width/height/type, y la Twitter Card sólo trae title (sin twitter:image ni twitter:description), por lo que el preview en X queda pobre.",
    "evidence": "De los artefactos y el template product_detail.html:\n\nog:image = https://gluck.nexttech.com.ar/media/products/1/.../787.jpg   (787x1400, vertical)\n# sin og:image:width / og:image:height / og:image:type\n# twitter:card=summary_large_image pero sin twitter:image ni twitter:description",
    "recommendation": "Para productos, generar/usar una og:image horizontal 1200x630 (1.91:1) — o un compuesto con la foto sobre fondo de marca — y declarar og:image:width/height/type. Completar twitter:image y twitter:description en la PDP.",
    "evidenceKind": "code",
    "status": "PENDIENTE",
  },
  {
    "id": "14",
    "title": "Títulos y meta descriptions de producto por debajo del largo ideal para la SERP",
    "severity": "low",
    "category": "Títulos / Descriptions",
    "dimension": "titles-meta",
    "scope": "Todas las PDP",
    "symptom": "Los títulos de producto miden 17-22 caracteres y las descriptions 52-61, ambos cortos para el espacio que da Google (title útil ~50-60, description ~120-160). Se desaprovecha espacio de SERP y palabras clave.",
    "evidence": "De los artefactos (titleLen / largo de metaDescription):",
    "recommendation": "Enriquecer con categoría, material y atributo (ej. «Tote Cognac · Cartera tote de cuero vegano hecha a mano | GLÜCK») y descriptions de 120-160 car. con beneficio + CTA. Mantenerlas únicas por producto.",
    "evidenceKind": "table",
    "evidenceTable": [
      {"URL": "/producto/1", "title (largo)": "Tote Cognac · GLÜCK (19)", "description (largo)": "54"},
      {"URL": "/producto/2", "title (largo)": "Tote Gris · GLÜCK (17)", "description (largo)": "52"},
      {"URL": "/producto/3", "title (largo)": "Crossbody Rosa · GLÜCK (22)", "description (largo)": "61"},
    ],
    "status": "PENDIENTE",
  },
  {
    "id": "15",
    "title": "LCP en 2,9 s (zona «a mejorar») por una imagen hero algo sobre-pesada",
    "severity": "low",
    "category": "Performance / CWV",
    "dimension": "performance-cwv",
    "scope": "Home (imagen hero = elemento LCP)",
    "symptom": "Lighthouse da Performance 94 y el resto de Core Web Vitals es excelente (CLS 0, TBT 10 ms, FCP 1,0 s), pero el LCP queda en 2,9 s — por encima del umbral «bueno» de 2,5 s. La imagen hero ya está precargada con fetchpriority=high (bien), así que el margen está en comprimirla mejor (~21 KB y ~150 ms recuperables).",
    "evidence": "Lighthouse (categorías seo+performance, headless):\n\nSEO:          100\nPerformance:  94\nLCP:          2.9 s   (a mejorar: > 2.5 s)\nFCP:          1.0 s\nCLS:          0\nTBT:          10 ms\n\n# La hero YA se precarga (fetchpriority=high) -> el arreglo es compresión, no preload.",
    "recommendation": "Recomprimir la imagen hero (AVIF/WebP a calidad adecuada, srcset por breakpoint) para bajar su peso sin perder nitidez y meter el LCP por debajo de 2,5 s. El resto de CWV ya está en verde.",
    "evidenceKind": "code",
    "status": "PENDIENTE",
  },
  {
    "id": "16",
    "title": "robots.txt: bloqueo de crawlers de IA (intencional, Cloudflare) — el rastreo de buscadores está permitido",
    "severity": "info",
    "category": "Crawl / robots.txt",
    "dimension": "indexability-crawl",
    "scope": "robots.txt",
    "symptom": "Nota de transparencia + corrección. El pase determinístico marcó «robots.txt bloquea todo el sitio (Disallow: /)» como CRÍTICO: es un FALSO POSITIVO. El Disallow: / está acotado a bots de IA nombrados (Amazonbot, GPTBot, ClaudeBot, Google-Extended, etc.), cada uno bajo su propio User-agent. Para User-agent: * la directiva es Allow: /. Googlebot y el rastreo de búsqueda están permitidos.",
    "evidence": "robots.txt (gestionado por Cloudflare):\n\nUser-agent: *\nContent-Signal: search=yes,ai-train=no\nAllow: /\n\nUser-agent: GPTBot\nDisallow: /\nUser-agent: ClaudeBot\nDisallow: /\nUser-agent: Google-Extended\nDisallow: /\n... (resto de bots de IA)\n\nUser-agent: *\nAllow: /",
    "recommendation": "No requiere acción salvo que se desee permitir el entrenamiento de IA. Es un ajuste deliberado de Cloudflare; el SEO de búsqueda no se ve afectado. Se incluye sólo para descartar el falso positivo.",
    "evidenceKind": "code",
    "status": "INFO",
  },
  {
    "id": "17",
    "title": "Sin verificación de Google Search Console en el sitio",
    "severity": "info",
    "category": "Medición / Confianza",
    "dimension": "measurement-trust",
    "scope": "Todo el sitio",
    "symptom": "No hay meta google-site-verification ni señal de propiedad verificada. Dado el problema de canonical cross-dominio (hallazgo 01), GSC es justamente la herramienta para monitorear qué dominio indexa Google y la cobertura por URL.",
    "evidence": "Home (curl): no aparece <meta name=\"google-site-verification\" ...>.",
    "recommendation": "Verificar gluckbags.com en Search Console (idealmente por DNS, que cubre todos los hosts), enviar el sitemap (hallazgo 04) y vigilar el informe de Páginas para confirmar que el canonical pase a apuntar a gluckbags.com.",
    "evidenceKind": "code",
    "status": "INFO",
  },
  {
    "id": "18",
    "title": "Dos sistemas de analítica de page views en paralelo: Umami + Cloudflare Web Analytics",
    "severity": "info",
    "category": "Medición / Confianza",
    "dimension": "measurement-trust",
    "scope": "Todo el sitio",
    "symptom": "El HTML incluye el script de Umami (analytics.nexttech.com.ar/script.js) y, además, Cloudflare inyecta en el edge su beacon de Web Analytics (cloudflareinsights.com/beacon.min.js). Dos sistemas midiendo lo mismo: duplica datos y suma un request extra.",
    "evidence": "Umami en el HTML servido:\n  <script ... src=\"https://analytics.nexttech.com.ar/script.js\" data-website-id=\"...\">\n\nBeacon de Cloudflare en el DOM renderizado (inyectado en el edge):\n  https://static.cloudflareinsights.com/beacon.min.js/v...",
    "recommendation": "Decidir una sola fuente de verdad. Si se usa Umami, desactivar Cloudflare Web Analytics (o viceversa) para no duplicar métricas ni cargar dos beacons.",
    "evidenceKind": "code",
    "status": "INFO",
  },
]

out = {
  "site": "https://gluckbags.com",
  "date": "2026-06-29",
  "summary": (
    "Relevamiento SEO exhaustivo de gluckbags.com (storefront Flask server-rendered, detrás de Cloudflare). "
    "Motor determinístico + fan-out multiagente con verificación adversarial de cada hallazgo contra el sitio vivo. "
    "Lo positivo: Lighthouse SEO 100 y Performance 94, CLS 0, TBT 10 ms, sin interstitials intrusivos, HTML rastreable sin brecha JS, un solo idioma (es-AR, sin hreflang necesario). "
    "Pero el sitio tiene un problema CRÍTICO que Lighthouse no detecta: el canonical y los datos sociales de TODO el dominio apuntan a un dominio gemelo vivo (gluck.nexttech.com.ar), así que la marca le cede su indexación al alias. "
    "Resuelto eso (un cambio de config SITE_URL), siguen: duplicación de host sin redirección, falta de sitemap, ausencia total de datos estructurados, sin páginas de confianza (E-E-A-T) y fichas de producto delgadas. "
    "Alcance: muestra representativa de tipos de página (home, 3 PDP, variantes con parámetros, 404), no el catálogo completo; los hallazgos por-URL valen como patrón. Backlinks/autoridad off-page y volumen real de indexación quedan fuera (requieren Ahrefs/GSC)."
  ),
  "findings": findings,
}

path = os.path.join(WORK, "findings.json")
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

sev_order = ["critical", "high", "medium", "low", "info"]
counts = {s: 0 for s in sev_order}
for fnd in findings:
    counts[fnd["severity"]] += 1
print(f"wrote {len(findings)} findings -> {path}")
print("  " + " · ".join(f"{counts[s]} {s}" for s in sev_order))
